services:
  reffindr.api:
    # image: igrowker/i004-reffindr-back-dotnet:prod
    build:
      context: .
      dockerfile: ./Reffindr.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"