name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: jamirgutierrezdelcarpio@gmail.com
        password: dckr_pat_ibDd3Bz1Q2bXvLyO8d78fi3zGwI

    - name: Build the Docker image
      run: docker build . --file ./Reffindr.Api/Dockerfile --tag dash977/reffindr:latest

    - name: Push the Docker image
      run: docker push dash977/reffindr:latest
    - name: App service auth
      uses: azure/webapps-deploy@v2
      with:
         app-name: 'Reffindr'
         publish-profile: <publishData><publishProfile profileName="Reffindr - Web Deploy" publishMethod="MSDeploy" publishUrl="reffindr-b7fjh3a3dugvcyet.scm.brazilsouth-01.azurewebsites.net:443" msdeploySite="Reffindr" userName="$Reffindr" userPWD="XnX0LErs0v3xWDseBRazgs73ogGxTBlDpuj3NfyxXd1wGpKBG6EFPZrmDolW" destinationAppUrl="https://reffindr-b7fjh3a3dugvcyet.brazilsouth-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="Reffindr - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-cq1-021.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="REDACTED" userPWD="REDACTED" destinationAppUrl="https://reffindr-b7fjh3a3dugvcyet.brazilsouth-01.azurewebsites.net" SQLServerDBConnectionString="REDACTED" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="Reffindr - Zip Deploy" publishMethod="ZipDeploy" publishUrl="reffindr-b7fjh3a3dugvcyet.scm.brazilsouth-01.azurewebsites.net:443" userName="$Reffindr" userPWD="XnX0LErs0v3xWDseBRazgs73ogGxTBlDpuj3NfyxXd1wGpKBG6EFPZrmDolW" destinationAppUrl="https://reffindr-b7fjh3a3dugvcyet.brazilsouth-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="Reffindr - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-cq1-021dr.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="REDACTED" userPWD="REDACTED" destinationAppUrl="https://reffindr-b7fjh3a3dugvcyet.brazilsouth-01.azurewebsites.net" SQLServerDBConnectionString="REDACTED" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
         images: 'dash977/reffindr:latest'
